//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_6.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.PRODUCTS = new ObservableCollection<PRODUCTS>();
            this.PRODUCTS1 = new ObservableCollection<PRODUCTS>();
            this.PRODUCTS2 = new ObservableCollection<PRODUCTS>();
        }
    
        public int ID_USER { get; set; }
        public string LOGIN_USER { get; set; }
        public string USER_TYPE { get; set; }
        public string PASSWORD_USER { get; set; }
        public Nullable<int> AVATAR_USER { get; set; }
    
        public virtual IMAGES IMAGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<PRODUCTS> PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<PRODUCTS> PRODUCTS1 { get; set; }
        public virtual USER_TYPE USER_TYPE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<PRODUCTS> PRODUCTS2 { get; set; }
    }
}
